export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	ADD_TODO: 'ADD_TODO',
	CHANGE_TODO: 'CHANGE_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	SET_IS_LOADING: 'SET_IS_LOADING',
	SET_ERROR_FETCH: 'SET_ERROR_FETCH',
	SET_ERROR_CREATION: 'SET_ERROR_CREATION',
};
